// flow-typed signature: 9dde18670e18d6e2d280e7c929d7fccc
// flow-typed version: <<STUB>>/connect-pg-simple_v^5.0.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect-pg-simple'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect-pg-simple' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'connect-pg-simple/test/db-utils' {
  declare module.exports: any;
}

declare module 'connect-pg-simple/test/integration/express.spec' {
  declare module.exports: any;
}

declare module 'connect-pg-simple/test/integration/pgpromise.spec' {
  declare module.exports: any;
}

declare module 'connect-pg-simple/test/main.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'connect-pg-simple/index' {
  declare module.exports: $Exports<'connect-pg-simple'>;
}
declare module 'connect-pg-simple/index.js' {
  declare module.exports: $Exports<'connect-pg-simple'>;
}
declare module 'connect-pg-simple/test/db-utils.js' {
  declare module.exports: $Exports<'connect-pg-simple/test/db-utils'>;
}
declare module 'connect-pg-simple/test/integration/express.spec.js' {
  declare module.exports: $Exports<'connect-pg-simple/test/integration/express.spec'>;
}
declare module 'connect-pg-simple/test/integration/pgpromise.spec.js' {
  declare module.exports: $Exports<'connect-pg-simple/test/integration/pgpromise.spec'>;
}
declare module 'connect-pg-simple/test/main.spec.js' {
  declare module.exports: $Exports<'connect-pg-simple/test/main.spec'>;
}
