// flow-typed signature: 8d2d1b0e3d15357e7fd6a2e6a97c5d2a
// flow-typed version: <<STUB>>/massive_v^5.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'massive'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'massive' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'massive/bin/massive' {
  declare module.exports: any;
}

declare module 'massive/lib/database' {
  declare module.exports: any;
}

declare module 'massive/lib/entity' {
  declare module.exports: any;
}

declare module 'massive/lib/executable' {
  declare module.exports: any;
}

declare module 'massive/lib/loader/functions' {
  declare module.exports: any;
}

declare module 'massive/lib/loader/scripts' {
  declare module.exports: any;
}

declare module 'massive/lib/loader/tables' {
  declare module.exports: any;
}

declare module 'massive/lib/loader/views' {
  declare module.exports: any;
}

declare module 'massive/lib/readable' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/delete' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/insert' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/mutators' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/operations' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/order-by' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/select' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/update' {
  declare module.exports: any;
}

declare module 'massive/lib/statement/where' {
  declare module.exports: any;
}

declare module 'massive/lib/util/decompose' {
  declare module.exports: any;
}

declare module 'massive/lib/util/docify' {
  declare module.exports: any;
}

declare module 'massive/lib/util/get-filter-string' {
  declare module.exports: any;
}

declare module 'massive/lib/util/parse-key' {
  declare module.exports: any;
}

declare module 'massive/lib/util/prepare-params' {
  declare module.exports: any;
}

declare module 'massive/lib/util/single-value-stream' {
  declare module.exports: any;
}

declare module 'massive/lib/writable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'massive/bin/massive.js' {
  declare module.exports: $Exports<'massive/bin/massive'>;
}
declare module 'massive/index' {
  declare module.exports: $Exports<'massive'>;
}
declare module 'massive/index.js' {
  declare module.exports: $Exports<'massive'>;
}
declare module 'massive/lib/database.js' {
  declare module.exports: $Exports<'massive/lib/database'>;
}
declare module 'massive/lib/entity.js' {
  declare module.exports: $Exports<'massive/lib/entity'>;
}
declare module 'massive/lib/executable.js' {
  declare module.exports: $Exports<'massive/lib/executable'>;
}
declare module 'massive/lib/loader/functions.js' {
  declare module.exports: $Exports<'massive/lib/loader/functions'>;
}
declare module 'massive/lib/loader/scripts.js' {
  declare module.exports: $Exports<'massive/lib/loader/scripts'>;
}
declare module 'massive/lib/loader/tables.js' {
  declare module.exports: $Exports<'massive/lib/loader/tables'>;
}
declare module 'massive/lib/loader/views.js' {
  declare module.exports: $Exports<'massive/lib/loader/views'>;
}
declare module 'massive/lib/readable.js' {
  declare module.exports: $Exports<'massive/lib/readable'>;
}
declare module 'massive/lib/statement/delete.js' {
  declare module.exports: $Exports<'massive/lib/statement/delete'>;
}
declare module 'massive/lib/statement/insert.js' {
  declare module.exports: $Exports<'massive/lib/statement/insert'>;
}
declare module 'massive/lib/statement/mutators.js' {
  declare module.exports: $Exports<'massive/lib/statement/mutators'>;
}
declare module 'massive/lib/statement/operations.js' {
  declare module.exports: $Exports<'massive/lib/statement/operations'>;
}
declare module 'massive/lib/statement/order-by.js' {
  declare module.exports: $Exports<'massive/lib/statement/order-by'>;
}
declare module 'massive/lib/statement/select.js' {
  declare module.exports: $Exports<'massive/lib/statement/select'>;
}
declare module 'massive/lib/statement/update.js' {
  declare module.exports: $Exports<'massive/lib/statement/update'>;
}
declare module 'massive/lib/statement/where.js' {
  declare module.exports: $Exports<'massive/lib/statement/where'>;
}
declare module 'massive/lib/util/decompose.js' {
  declare module.exports: $Exports<'massive/lib/util/decompose'>;
}
declare module 'massive/lib/util/docify.js' {
  declare module.exports: $Exports<'massive/lib/util/docify'>;
}
declare module 'massive/lib/util/get-filter-string.js' {
  declare module.exports: $Exports<'massive/lib/util/get-filter-string'>;
}
declare module 'massive/lib/util/parse-key.js' {
  declare module.exports: $Exports<'massive/lib/util/parse-key'>;
}
declare module 'massive/lib/util/prepare-params.js' {
  declare module.exports: $Exports<'massive/lib/util/prepare-params'>;
}
declare module 'massive/lib/util/single-value-stream.js' {
  declare module.exports: $Exports<'massive/lib/util/single-value-stream'>;
}
declare module 'massive/lib/writable.js' {
  declare module.exports: $Exports<'massive/lib/writable'>;
}
